name: bEnchants
version: 1.0.2
main: com.bfrisco.benchants.BEnchants
author: bfrisco
description: bEnchants custom enchants
api-version: 1.17
depend: [NBTAPI]

commands:
  bactivate:
  benchants:
    description: Enchants an item
    usage: |
      /<command> <apply|remove> <enchant>
      /<command> reload
      /<command> <toggle>

permissions:
  benchants.enchant:
    description: Allows player to enchant items with trench
    default: op
  benchants.toggle:
    description: Allows a player to toggle ancient power